{% set name = "caf.space" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.space-{{ version }}.tar.gz
  sha256: 905fb2e2002d9241f8b8ca4cee39fac7be2c0dbbe9a115143efd5d852a268453

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools_scm
    - versioneer-518
    - versioneer
    - pip
  run:
    - python >=3.9
    - caf.toolkit >=0.0.7
    - geopandas >=0.9
    - fiona >=1.8
    - shapely >=1.8
    - numpy >=1.21
    - pandas >=1.3
    - pydantic >=1.10.2
    - openpyxl >=3.0
    - tkinterweb >=3.17

test:
  imports:
    - caf.space
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.space
  summary: Easily generate translations between transport zoning systems
  dev_url: https://github.com/Transport-for-the-North/caf.space
  license: GPL-3.0
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JustinScottJenecke
    - isaac-tfn
